config/routes.rb
Rails.application.routes.draw do
  resources :echellons

  resources :persoclas

  resources :persocates

  devise_for :users
  resources :deces

  resources :mariages

  resources :naissances

  get 'welcome/home'
  root 'welcome#home'

  resources :permissions

  resources :personnels

  resources :services

  resources :centres

end

app/models/centre.rb
class Centre < ActiveRecord::Base
	has_many :personnel
end

app/models/dece.rb
class Dece < ActiveRecord::Base
end

app/models/echellon.rb
class Echellon < ActiveRecord::Base
  belongs_to :persocla
end

app/models/mariage.rb
class Mariage < ActiveRecord::Base
end

app/models/naissance.rb
class Naissance < ActiveRecord::Base
end

app/models/permission.rb
class Permission < ActiveRecord::Base
end

app/models/persocate.rb
class Persocate < ActiveRecord::Base
end

app/models/persocla.rb
class Persocla < ActiveRecord::Base
  belongs_to :persocate
end

app/models/personnel.rb
class Personnel < ActiveRecord::Base
	default_scope {order(:id)}

	belongs_to :centre
	belongs_to :service

	has_attached_file :cover, 
      	:styles => { 
	    :medium => "300x300>", 
	    :thumb => "100x100>" }, 
	    :default_url => "/public/system/images.jpg"
  validates_attachment_content_type :cover, :content_type => /\Aimage\/.*\Z/


end

app/models/service.rb
class Service < ActiveRecord::Base
	has_many :personnel
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/persocates_controller.rb
class PersocatesController < ApplicationController
  before_action :set_persocate, only: [:show, :edit, :update, :destroy]

  # GET /persocates
  # GET /persocates.json
  def index
    @persocates = Persocate.all
  end

  # GET /persocates/1
  # GET /persocates/1.json
  def show
  end

  # GET /persocates/new
  def new
    @persocate = Persocate.new
  end

  # GET /persocates/1/edit
  def edit
  end

  # POST /persocates
  # POST /persocates.json
  def create
    @persocate = Persocate.new(persocate_params)

    respond_to do |format|
      if @persocate.save
        format.html { redirect_to @persocate, notice: 'Persocate was successfully created.' }
        format.json { render :show, status: :created, location: @persocate }
      else
        format.html { render :new }
        format.json { render json: @persocate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /persocates/1
  # PATCH/PUT /persocates/1.json
  def update
    respond_to do |format|
      if @persocate.update(persocate_params)
        format.html { redirect_to @persocate, notice: 'Persocate was successfully updated.' }
        format.json { render :show, status: :ok, location: @persocate }
      else
        format.html { render :edit }
        format.json { render json: @persocate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /persocates/1
  # DELETE /persocates/1.json
  def destroy
    @persocate.destroy
    respond_to do |format|
      format.html { redirect_to persocates_url, notice: 'Persocate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_persocate
      @persocate = Persocate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def persocate_params
      params.require(:persocate).permit(:nom_cate, :type_cat)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/centres_helper.rb
module CentresHelper
end

app/helpers/deces_helper.rb
module DecesHelper
end

app/helpers/echellons_helper.rb
module EchellonsHelper
end

app/helpers/mariages_helper.rb
module MariagesHelper
end

app/helpers/naissances_helper.rb
module NaissancesHelper
end

app/helpers/persocates_helper.rb
module PersocatesHelper
end

app/helpers/persoclas_helper.rb
module PersoclasHelper
end

app/helpers/personnels_helper.rb
module PersonnelsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/persocates/_form.html.erb
<%= simple_form_for(@persocate) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nom_cate %>
    <%= f.input :type_cat %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/persocates/edit.html.erb
<h1>Editing persocate</h1>

<%= render 'form' %>

<%= link_to 'Show', @persocate %> |
<%= link_to 'Back', persocates_path %>

app/views/persocates/index.html.erb
<h1>Listing persocates</h1>

<table>
  <thead>
    <tr>
      <th>Nom cate</th>
      <th>Type cat</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @persocates.each do |persocate| %>
      <tr>
        <td><%= persocate.nom_cate %></td>
        <td><%= persocate.type_cat %></td>
        <td><%= link_to 'Show', persocate %></td>
        <td><%= link_to 'Edit', edit_persocate_path(persocate) %></td>
        <td><%= link_to 'Destroy', persocate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Persocate', new_persocate_path %>

app/views/persocates/new.html.erb
<h1>New persocate</h1>

<%= render 'form' %>

<%= link_to 'Back', persocates_path %>

app/views/persocates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom cate:</strong>
  <%= @persocate.nom_cate %>
</p>

<p>
  <strong>Type cat:</strong>
  <%= @persocate.type_cat %>
</p>

<%= link_to 'Edit', edit_persocate_path(@persocate) %> |
<%= link_to 'Back', persocates_path %>