config/routes.rb
Rails.application.routes.draw do
  resources :echellons

  resources :persoclas

  resources :persocates

  devise_for :users
  resources :deces

  resources :mariages

  resources :naissances

  get 'welcome/home'
  root 'welcome#home'

  resources :permissions

  resources :personnels

  resources :services

  resources :centres

end

app/models/centre.rb
class Centre < ActiveRecord::Base
	has_many :personnel
end

app/models/dece.rb
class Dece < ActiveRecord::Base
end

app/models/echellon.rb
class Echellon < ActiveRecord::Base
  belongs_to :persocla
end

app/models/mariage.rb
class Mariage < ActiveRecord::Base
end

app/models/naissance.rb
class Naissance < ActiveRecord::Base
end

app/models/permission.rb
class Permission < ActiveRecord::Base
end

app/models/persocate.rb
class Persocate < ActiveRecord::Base
end

app/models/persocla.rb
class Persocla < ActiveRecord::Base
  belongs_to :persocate
end

app/models/personnel.rb
class Personnel < ActiveRecord::Base
	default_scope {order(:id)}

	belongs_to :centre
	belongs_to :service

	has_attached_file :cover, 
      	:styles => { 
	    :medium => "300x300>", 
	    :thumb => "100x100>" }, 
	    :default_url => "/public/system/images.jpg"
  validates_attachment_content_type :cover, :content_type => /\Aimage\/.*\Z/


end

app/models/service.rb
class Service < ActiveRecord::Base
	has_many :personnel
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/persoclas_controller.rb
class PersoclasController < ApplicationController
  before_action :set_persocla, only: [:show, :edit, :update, :destroy]

  # GET /persoclas
  # GET /persoclas.json
  def index
    @persoclas = Persocla.all
  end

  # GET /persoclas/1
  # GET /persoclas/1.json
  def show
  end

  # GET /persoclas/new
  def new
    @persocla = Persocla.new
  end

  # GET /persoclas/1/edit
  def edit
  end

  # POST /persoclas
  # POST /persoclas.json
  def create
    @persocla = Persocla.new(persocla_params)

    respond_to do |format|
      if @persocla.save
        format.html { redirect_to @persocla, notice: 'Persocla was successfully created.' }
        format.json { render :show, status: :created, location: @persocla }
      else
        format.html { render :new }
        format.json { render json: @persocla.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /persoclas/1
  # PATCH/PUT /persoclas/1.json
  def update
    respond_to do |format|
      if @persocla.update(persocla_params)
        format.html { redirect_to @persocla, notice: 'Persocla was successfully updated.' }
        format.json { render :show, status: :ok, location: @persocla }
      else
        format.html { render :edit }
        format.json { render json: @persocla.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /persoclas/1
  # DELETE /persoclas/1.json
  def destroy
    @persocla.destroy
    respond_to do |format|
      format.html { redirect_to persoclas_url, notice: 'Persocla was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_persocla
      @persocla = Persocla.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def persocla_params
      params.require(:persocla).permit(:persocate_id, :num_cla)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/centres_helper.rb
module CentresHelper
end

app/helpers/deces_helper.rb
module DecesHelper
end

app/helpers/echellons_helper.rb
module EchellonsHelper
end

app/helpers/mariages_helper.rb
module MariagesHelper
end

app/helpers/naissances_helper.rb
module NaissancesHelper
end

app/helpers/persocates_helper.rb
module PersocatesHelper
end

app/helpers/persoclas_helper.rb
module PersoclasHelper
end

app/helpers/personnels_helper.rb
module PersonnelsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/persoclas/_form.html.erb
<%= simple_form_for(@persocla) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :persocate %>
    <%= f.input :num_cla %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/persoclas/edit.html.erb
<h1>Editing persocla</h1>

<%= render 'form' %>

<%= link_to 'Show', @persocla %> |
<%= link_to 'Back', persoclas_path %>

app/views/persoclas/index.html.erb
<h1>Listing persoclas</h1>

<table>
  <thead>
    <tr>
      <th>Persocate</th>
      <th>Num cla</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @persoclas.each do |persocla| %>
      <tr>
        <td><%= persocla.persocate %></td>
        <td><%= persocla.num_cla %></td>
        <td><%= link_to 'Show', persocla %></td>
        <td><%= link_to 'Edit', edit_persocla_path(persocla) %></td>
        <td><%= link_to 'Destroy', persocla, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Persocla', new_persocla_path %>

app/views/persoclas/new.html.erb
<h1>New persocla</h1>

<%= render 'form' %>

<%= link_to 'Back', persoclas_path %>

app/views/persoclas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Persocate:</strong>
  <%= @persocla.persocate %>
</p>

<p>
  <strong>Num cla:</strong>
  <%= @persocla.num_cla %>
</p>

<%= link_to 'Edit', edit_persocla_path(@persocla) %> |
<%= link_to 'Back', persoclas_path %>