config/routes.rb
Rails.application.routes.draw do
  resources :echellons

  resources :persoclas

  resources :persocates

  devise_for :users
  resources :deces

  resources :mariages

  resources :naissances

  get 'welcome/home'
  root 'welcome#home'

  resources :permissions

  resources :personnels

  resources :services

  resources :centres

end

app/models/centre.rb
class Centre < ActiveRecord::Base
	has_many :personnel
end

app/models/dece.rb
class Dece < ActiveRecord::Base
end

app/models/echellon.rb
class Echellon < ActiveRecord::Base
  belongs_to :persocla
end

app/models/mariage.rb
class Mariage < ActiveRecord::Base
end

app/models/naissance.rb
class Naissance < ActiveRecord::Base
end

app/models/permission.rb
class Permission < ActiveRecord::Base
end

app/models/persocate.rb
class Persocate < ActiveRecord::Base
end

app/models/persocla.rb
class Persocla < ActiveRecord::Base
  belongs_to :persocate
end

app/models/personnel.rb
class Personnel < ActiveRecord::Base
	default_scope {order(:id)}

	belongs_to :centre
	belongs_to :service

	has_attached_file :cover, 
      	:styles => { 
	    :medium => "300x300>", 
	    :thumb => "100x100>" }, 
	    :default_url => "/public/system/images.jpg"
  validates_attachment_content_type :cover, :content_type => /\Aimage\/.*\Z/


end

app/models/service.rb
class Service < ActiveRecord::Base
	has_many :personnel
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/echellons_controller.rb
class EchellonsController < ApplicationController
  before_action :set_echellon, only: [:show, :edit, :update, :destroy]

  # GET /echellons
  # GET /echellons.json
  def index
    @echellons = Echellon.all
  end

  # GET /echellons/1
  # GET /echellons/1.json
  def show
  end

  # GET /echellons/new
  def new
    @echellon = Echellon.new
  end

  # GET /echellons/1/edit
  def edit
  end

  # POST /echellons
  # POST /echellons.json
  def create
    @echellon = Echellon.new(echellon_params)

    respond_to do |format|
      if @echellon.save
        format.html { redirect_to @echellon, notice: 'Echellon was successfully created.' }
        format.json { render :show, status: :created, location: @echellon }
      else
        format.html { render :new }
        format.json { render json: @echellon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /echellons/1
  # PATCH/PUT /echellons/1.json
  def update
    respond_to do |format|
      if @echellon.update(echellon_params)
        format.html { redirect_to @echellon, notice: 'Echellon was successfully updated.' }
        format.json { render :show, status: :ok, location: @echellon }
      else
        format.html { render :edit }
        format.json { render json: @echellon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /echellons/1
  # DELETE /echellons/1.json
  def destroy
    @echellon.destroy
    respond_to do |format|
      format.html { redirect_to echellons_url, notice: 'Echellon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_echellon
      @echellon = Echellon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def echellon_params
      params.require(:echellon).permit(:persocla_id, :num_echellon, :salaire_indice)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/centres_helper.rb
module CentresHelper
end

app/helpers/deces_helper.rb
module DecesHelper
end

app/helpers/echellons_helper.rb
module EchellonsHelper
end

app/helpers/mariages_helper.rb
module MariagesHelper
end

app/helpers/naissances_helper.rb
module NaissancesHelper
end

app/helpers/persocates_helper.rb
module PersocatesHelper
end

app/helpers/persoclas_helper.rb
module PersoclasHelper
end

app/helpers/personnels_helper.rb
module PersonnelsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/echellons/_form.html.erb
<%= simple_form_for(@echellon) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :persocla %>
    <%= f.input :num_echellon %>
    <%= f.input :salaire_indice %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/echellons/edit.html.erb
<h1>Editing echellon</h1>

<%= render 'form' %>

<%= link_to 'Show', @echellon %> |
<%= link_to 'Back', echellons_path %>

app/views/echellons/index.html.erb
<h1>Listing echellons</h1>

<table>
  <thead>
    <tr>
      <th>Persocla</th>
      <th>Num echellon</th>
      <th>Salaire indice</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @echellons.each do |echellon| %>
      <tr>
        <td><%= echellon.persocla %></td>
        <td><%= echellon.num_echellon %></td>
        <td><%= echellon.salaire_indice %></td>
        <td><%= link_to 'Show', echellon %></td>
        <td><%= link_to 'Edit', edit_echellon_path(echellon) %></td>
        <td><%= link_to 'Destroy', echellon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Echellon', new_echellon_path %>

app/views/echellons/new.html.erb
<h1>New echellon</h1>

<%= render 'form' %>

<%= link_to 'Back', echellons_path %>

app/views/echellons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Persocla:</strong>
  <%= @echellon.persocla %>
</p>

<p>
  <strong>Num echellon:</strong>
  <%= @echellon.num_echellon %>
</p>

<p>
  <strong>Salaire indice:</strong>
  <%= @echellon.salaire_indice %>
</p>

<%= link_to 'Edit', edit_echellon_path(@echellon) %> |
<%= link_to 'Back', echellons_path %>