config/routes.rb
Rails.application.routes.draw do
  resources :echellons

  resources :persoclas

  resources :persocates

  devise_for :users
  resources :deces

  resources :mariages

  resources :naissances

  get 'welcome/home'
  root 'welcome#home'

  resources :permissions

  resources :personnels

  resources :services

  resources :centres

end

app/models/centre.rb
class Centre < ActiveRecord::Base
	has_many :personnel
end

app/models/dece.rb
class Dece < ActiveRecord::Base
end

app/models/echellon.rb
class Echellon < ActiveRecord::Base
  belongs_to :persocla
end

app/models/mariage.rb
class Mariage < ActiveRecord::Base
end

app/models/naissance.rb
class Naissance < ActiveRecord::Base
end

app/models/permission.rb
class Permission < ActiveRecord::Base
end

app/models/persocate.rb
class Persocate < ActiveRecord::Base
end

app/models/persocla.rb
class Persocla < ActiveRecord::Base
  belongs_to :persocate
end

app/models/personnel.rb
class Personnel < ActiveRecord::Base
	default_scope {order(:id)}

	belongs_to :centre
	belongs_to :service

	has_attached_file :cover, 
      	:styles => { 
	    :medium => "300x300>", 
	    :thumb => "100x100>" }, 
	    :default_url => "/public/system/images.jpg"
  validates_attachment_content_type :cover, :content_type => /\Aimage\/.*\Z/


end

app/models/service.rb
class Service < ActiveRecord::Base
	has_many :personnel
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/centres_controller.rb
class CentresController < ApplicationController
  before_action :set_centre, only: [:show, :edit, :update, :destroy]

  # GET /centres
  # GET /centres.json
  def index
    @centres = Centre.all
  end

  # GET /centres/1
  # GET /centres/1.json
  def show
  end

  # GET /centres/new
  def new
    @centre = Centre.new
  end

  # GET /centres/1/edit
  def edit
  end

  # POST /centres
  # POST /centres.json
  def create
    @centre = Centre.new(centre_params)

    respond_to do |format|
      if @centre.save
        format.html { redirect_to @centre, notice: 'Centre was successfully created.' }
        format.json { render :show, status: :created, location: @centre }
      else
        format.html { render :new }
        format.json { render json: @centre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /centres/1
  # PATCH/PUT /centres/1.json
  def update
    respond_to do |format|
      if @centre.update(centre_params)
        format.html { redirect_to @centre, notice: 'Centre was successfully updated.' }
        format.json { render :show, status: :ok, location: @centre }
      else
        format.html { render :edit }
        format.json { render json: @centre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /centres/1
  # DELETE /centres/1.json
  def destroy
    @centre.destroy
    respond_to do |format|
      format.html { redirect_to centres_url, notice: 'Centre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_centre
      @centre = Centre.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def centre_params
      params.require(:centre).permit(:nom_centre, :phone, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/centres_helper.rb
module CentresHelper
end

app/helpers/deces_helper.rb
module DecesHelper
end

app/helpers/echellons_helper.rb
module EchellonsHelper
end

app/helpers/mariages_helper.rb
module MariagesHelper
end

app/helpers/naissances_helper.rb
module NaissancesHelper
end

app/helpers/persocates_helper.rb
module PersocatesHelper
end

app/helpers/persoclas_helper.rb
module PersoclasHelper
end

app/helpers/personnels_helper.rb
module PersonnelsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/centres/_form.html.erb
<%= simple_form_for @centre, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :nom_centre %>
  <%= f.input :phone %>
  <%= f.input :address %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                centres_path, :class => 'btn' %>
  </div>
<% end %>

app/views/centres/edit.html.erb
<%- model_class = Centre -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/centres/index.html.erb
<%- model_class = Centre -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nom_centre) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
  
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @centres.each do |centre| %>
      <tr>
        <td><%= link_to centre.id, centre_path(centre) %></td>
        <td><%= centre.nom_centre %></td>
        <td><%= centre.phone %></td>
        <td><%= centre.address %></td>
    
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_centre_path(centre), :class => 'btn btn-primary btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      centre_path(centre),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-danger btn-xs' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_centre_path,
            :class => 'btn btn-primary' %>

app/views/centres/new.html.erb
<%- model_class = Centre -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/centres/show.html.erb
<%- model_class = Centre -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nom_centre) %>:</strong></dt>
  <dd><%= @centre.nom_centre %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phone) %>:</strong></dt>
  <dd><%= @centre.phone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @centre.address %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              centres_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_centre_path(@centre), :class => 'btn btn-primary' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              centre_path(@centre),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>